cam = 0
zbar_status = None
message = 'Get close QR code to cam'
last_message = 'Get close QR code to cam'
beginning_game = True
item = None
name = "hola"
change_item = True
game_points = 0
game_success = 0
game_fail = 0
game_objects = None
game_initialized = False
game_number_objects = -1
message_alert = "alert-info"
game_image = "/files/static/Who.png"
game_image_prev = ""
game_last_image = ""
game_file = ""
game_display = "none"
game_reload = True
fail_flag = False
cam_width = 320
cam_height = 240
cam_refresh = 2000
match = 0
rfid_code = 'No code read'
timestart = 0
timeend = 0
correct = 0
fail = 0
identifier = 0
thera_indi = None
failsong='/files/songs/fail.mp3'
end=0
