# Generated by Django 2.0.7 on 2018-09-01 23:11

import appQRMusical.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('proposito', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Actividad_Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Asigna_Terapia',
            fields=[
                ('id_asign_therapy', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria_Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Actividad')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id_contenido', models.AutoField(primary_key=True, serialize=False)),
                ('desripcion', models.CharField(blank=True, max_length=50)),
                ('codigo', models.CharField(blank=True, max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id_diagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('valoracion', models.CharField(blank=True, max_length=50)),
                ('notas', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Especialista_Asigna_Terapia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('asigna_terapia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Asigna_Terapia')),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Especialista')),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id_indicador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, upload_to='profiles/')),
                ('nombre', models.CharField(max_length=50, verbose_name='Name')),
                ('apellido', models.CharField(max_length=50, verbose_name='Surname')),
                ('fecha_de_nacimiento', models.DateField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, verbose_name=appQRMusical.models.calcular_edad)),
                ('genero', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10)),
                ('nivel', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=1)),
                ('codigo', models.CharField(blank=True, max_length=8)),
                ('online', models.CharField(choices=[('si', 'si'), ('no', 'no')], default='no', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado_Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.TextField(blank=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Actividad')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Indicador')),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id_sesion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('asigna_Terapia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Asigna_Terapia')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Especialista')),
            ],
        ),
        migrations.CreateModel(
            name='Terapia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Terapia_Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Actividad')),
                ('terapia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Terapia')),
            ],
        ),
        migrations.CreateModel(
            name='Terapia_Indicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Indicador')),
                ('terapia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Terapia')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activado', models.BooleanField(default=False)),
                ('paciente', models.ManyToManyField(to='appQRMusical.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('contenido_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appQRMusical.Contenido')),
                ('nombre', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to=appQRMusical.models.directory_to_upload)),
                ('imagen', models.ImageField(upload_to='images/')),
                ('filetype', models.CharField(max_length=3)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('datetime',),
            },
            bases=('appQRMusical.contenido',),
        ),
        migrations.CreateModel(
            name='Texto',
            fields=[
                ('contenido_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appQRMusical.Contenido')),
                ('data', models.CharField(blank=True, max_length=50)),
            ],
            bases=('appQRMusical.contenido',),
        ),
        migrations.AddField(
            model_name='supervisa',
            name='tratamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Tratamiento'),
        ),
        migrations.AddField(
            model_name='resultado_sesion',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Sesion'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Paciente'),
        ),
        migrations.AddField(
            model_name='asigna_terapia',
            name='terapia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Terapia'),
        ),
        migrations.AddField(
            model_name='asigna_terapia',
            name='tratamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Tratamiento'),
        ),
        migrations.AddField(
            model_name='actividad_contenido',
            name='contenido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Contenido'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='indicador',
            field=models.ManyToManyField(blank=True, to='appQRMusical.Indicador'),
        ),
        migrations.AlterUniqueTogether(
            name='terapia_indicador',
            unique_together={('terapia', 'indicador')},
        ),
        migrations.AlterUniqueTogether(
            name='terapia_actividad',
            unique_together={('actividad', 'terapia')},
        ),
        migrations.AlterUniqueTogether(
            name='supervisa',
            unique_together={('especialista', 'tratamiento')},
        ),
        migrations.AlterUniqueTogether(
            name='resultado_sesion',
            unique_together={('sesion', 'indicador', 'actividad')},
        ),
        migrations.AlterUniqueTogether(
            name='especialista_asigna_terapia',
            unique_together={('asigna_terapia', 'especialista', 'fecha')},
        ),
        migrations.AlterUniqueTogether(
            name='categoria_actividad',
            unique_together={('categoria', 'actividad')},
        ),
        migrations.AlterUniqueTogether(
            name='actividad_contenido',
            unique_together={('actividad', 'contenido')},
        ),
    ]
