# Generated by Django 2.0.3 on 2018-06-17 18:08

import appQRMusical.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asign_Therapy',
            fields=[
                ('id_asign_therapy', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category_Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id_content', models.AutoField(primary_key=True, serialize=False)),
                ('desription', models.CharField(blank=True, max_length=50)),
                ('code', models.CharField(blank=True, max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id_diagnostic', models.AutoField(primary_key=True, serialize=False)),
                ('assesment', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id_indicator', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('purpose', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player_Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Player_Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Indicator')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(default=0, verbose_name='Age')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=1)),
                ('code', models.CharField(blank=True, max_length=8)),
                ('online', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Result_Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(blank=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Indicator')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id_session', models.AutoField(primary_key=True, serialize=False)),
                ('asign_therapy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Asign_Therapy')),
            ],
        ),
        migrations.CreateModel(
            name='Supervise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Therapist_Asign_Therapy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('asign_therapy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Asign_Therapy')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Therapist')),
            ],
        ),
        migrations.CreateModel(
            name='Therapy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True)),
                ('therapy_type', models.CharField(max_length=50, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Therapy_Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Indicator')),
                ('therapy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Therapy')),
            ],
        ),
        migrations.CreateModel(
            name='Therapy_Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Player')),
                ('therapy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Therapy')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appQRMusical.Content')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to=appQRMusical.models.directory_to_upload)),
                ('image', models.ImageField(upload_to='images/')),
                ('filetype', models.CharField(max_length=3)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('datetime',),
            },
            bases=('appQRMusical.content',),
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appQRMusical.Content')),
                ('data', models.CharField(blank=True, max_length=50)),
            ],
            bases=('appQRMusical.content',),
        ),
        migrations.AddField(
            model_name='supervise',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Therapist'),
        ),
        migrations.AddField(
            model_name='supervise',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Treatment'),
        ),
        migrations.AddField(
            model_name='result_session',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Session'),
        ),
        migrations.AddField(
            model_name='player_content',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Content'),
        ),
        migrations.AddField(
            model_name='player_content',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Player'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Profile'),
        ),
        migrations.AddField(
            model_name='category_player',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Player'),
        ),
        migrations.AddField(
            model_name='asign_therapy',
            name='therapy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Therapy'),
        ),
        migrations.AddField(
            model_name='asign_therapy',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Treatment'),
        ),
        migrations.AlterUniqueTogether(
            name='therapy_player',
            unique_together={('player', 'therapy')},
        ),
        migrations.AlterUniqueTogether(
            name='therapy_indicator',
            unique_together={('therapy', 'indicator')},
        ),
        migrations.AlterUniqueTogether(
            name='therapist_asign_therapy',
            unique_together={('asign_therapy', 'therapist', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='supervise',
            unique_together={('therapist', 'treatment')},
        ),
        migrations.AlterUniqueTogether(
            name='result_session',
            unique_together={('session', 'indicator', 'player')},
        ),
        migrations.AlterUniqueTogether(
            name='player_indicator',
            unique_together={('player', 'indicator')},
        ),
        migrations.AlterUniqueTogether(
            name='player_content',
            unique_together={('player', 'content')},
        ),
        migrations.AlterUniqueTogether(
            name='category_player',
            unique_together={('category', 'player')},
        ),
    ]
