# Generated by Django 2.0.3 on 2018-06-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='purpose',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
