# Generated by Django 2.0.3 on 2018-06-26 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0002_auto_20180617_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
