# Generated by Django 2.0.7 on 2018-09-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0002_auto_20180902_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asigna_terapia',
            name='terapia',
        ),
        migrations.AddField(
            model_name='asigna_terapia',
            name='terapia',
            field=models.ManyToManyField(to='appQRMusical.Terapia'),
        ),
    ]
