# Generated by Django 2.0.7 on 2018-08-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0003_session_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='profiles/'),
        ),
    ]
