# Generated by Django 2.0.7 on 2018-09-02 02:00

import appQRMusical.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0003_auto_20180902_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.IntegerField(blank=True, null=True, verbose_name=appQRMusical.models.calcular_edad),
        ),
    ]
