# Generated by Django 2.0.7 on 2018-09-02 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0005_auto_20180902_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialista',
            old_name='Apellido',
            new_name='apellido',
        ),
        migrations.RemoveField(
            model_name='tratamiento',
            name='paciente',
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Paciente'),
            preserve_default=False,
        ),
    ]
